apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
  - manifests/configmap.yaml
  - manifests/deployment.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
images:
  - name: log-getter-image
    newName: eplol/log-getter
    newTag: latest

  - name: log-writer-image
    newName: eplol/log-writer
    newTag: latest