apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
spec:
  strategy:
      type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: project-image-claim
      containers:
        - name: todo-app
          image: todo-app-image
          volumeMounts:
          - name: shared-image
            mountPath: /mydir/shared/files
          env:
          - name: PORT
            value: "8000"
          - name: PICSUM_URL
            valueFrom:
              configMapKeyRef:
                name: project-configmap
                key: PICSUM_URL
          - name: TODOS_URL
            valueFrom:
              configMapKeyRef:
                name: project-configmap
                key: TODOS_URL