apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-image
          emptyDir: {}
        - name: config
          configMap:
            name: log-configmap
      containers:
        - name: log-writer
          image: eplol/log-writer:1.1
          volumeMounts:
          - name: shared-image
            mountPath: /mydir/shared/files
          env:
          - name: "PORT"
            value: "3000"
        - name: log-getter
          image: eplol/log-getter:3.1
          volumeMounts:
          - name: shared-image
            mountPath: /mydir/shared/files
          - name: config
            mountPath: "/config"
          env:
          - name: "PORT"
            value: "3000"
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: log-configmap
                key: MESSAGE
