apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-claim
  namespace: exercises
spec:
  storageClassName: my-example-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi