apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-rate
  namespace: exercises
spec:
  metrics:
  - name: cpu-rate
    initialDelay: 2m
    interval: 1m
    successCondition: result[0] < 0.3
    failureLimit: 1
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1769-prometheus.prometheus.svc.cluster.local:9090
        query: |
          sum(
            rate(container_cpu_usage_seconds_total{namespace="exercises", container!=""}[5m])
          )