apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging


patches:
- patch: |-
    $patch: delete
    apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: backup-cronjob
  target:
    kind: CronJob
    name: backup-cronjob
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "none"
  target:
    kind: Deployment
    name: broadcaster-dep

      
images:
- name: broadcaster-image
  newName: eplol/broadcaster
  newTag: 932e516e549d2ac6c8a7354a5c9c69c6928e3140
- name: todo-app-image
  newName: eplol/todo-app
  newTag: 932e516e549d2ac6c8a7354a5c9c69c6928e3140
- name: todo-backend-image
  newName: eplol/todo-backend
  newTag: 932e516e549d2ac6c8a7354a5c9c69c6928e3140
