apiVersion: v1
kind: ConfigMap
metadata:
  name: project-configmap
  namespace: project
data:
  PICSUM_URL: https://picsum.photos/1200
  TODOS_URL: http://todo-backend-svc:2347/todos
  REDIRECT_URL: /