apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-image-claim
spec:
  storageClassName: my-project-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi