apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - todo-app/manifests/configmap.yaml
  - todo-backend/manifests/statefulset.yaml
  - todo-app/manifests/deployment.yaml
  - todo-app/manifests/ingress.yaml
  - todo-app/manifests/persistentvolumeclaim.yaml
  - todo-app/manifests/service.yaml
  - todo-backend/manifests/deployment.yaml
  - todo-backend/manifests/service.yaml
  - todo-backend/manifests/todo-cronjob.yaml
  #- todo-backend/manifests/backup-cronjob.yaml
  - broadcaster/manifests/deployment.yaml
  
images:
  - name: todo-app-image
    newName: eplol/todo-app
    newTag: latest

  - name: todo-backend-image
    newName: eplol/todo-backend
    newTag: latest

  - name: broadcaster-image
    newName: eplol/broadcaster
    newTag: latest