apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
  #- todo-backend/manifests/backup-cronjob.yaml
resources:
- todo-app/manifests/configmap.yaml
- todo-backend/manifests/statefulset.yaml
- todo-app/manifests/deployment.yaml
- todo-app/manifests/ingress.yaml
- todo-app/manifests/persistentvolumeclaim.yaml
- todo-app/manifests/service.yaml
- todo-backend/manifests/deployment.yaml
- todo-backend/manifests/service.yaml
- todo-backend/manifests/todo-cronjob.yaml
- broadcaster/manifests/deployment.yaml
  


images:
- name: broadcaster-image
  newName: eplol/broadcaster
  newTag: a4da34598ccc9cf6f4e420fe0114279c1bccd20d
- name: todo-app-image
  newName: eplol/todo-app
  newTag: a4da34598ccc9cf6f4e420fe0114279c1bccd20d
- name: todo-backend-image
  newName: eplol/todo-backend
  newTag: a4da34598ccc9cf6f4e420fe0114279c1bccd20d
