apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: project-postgres-ss
  namespace: project
spec:
  serviceName: "project-postgres-svc"
  replicas: 1
  selector:
    matchLabels:
      app: project-postgres
  template:
    metadata:
      labels:
        app: project-postgres
    spec:
      containers:
      - name: project-postgres
        image: postgres:16
        env:
        - name: POSTGRES_PASSWORD
          value: "pass123"
        - name: POSTGRES_DB
          value: "postgres"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi