apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: production

images:
- name: broadcaster-image
  newName: eplol/broadcaster
  newTag: 9e33fc38de0ffbf921df0e637851ecb8eda16908
- name: todo-app-image
  newName: eplol/todo-app
  newTag: 9e33fc38de0ffbf921df0e637851ecb8eda16908
- name: todo-backend-image
  newName: eplol/todo-backend
  newTag: 9e33fc38de0ffbf921df0e637851ecb8eda16908
