name: Build and publish application

on:
  push:
    branches:
        - "4.7"
jobs:
  build-publish-getter:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish backend
        run: |-
          cd log-output
          cd log-getter
          docker build --tag "eplol/log-getter:$GITHUB_SHA" .
          docker push "eplol/log-getter:$GITHUB_SHA"
          cd ..
          cd log-writer
          docker build --tag "eplol/log-writer:$GITHUB_SHA" .
          docker push "eplol/log-writer:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update image tags
        run: |-
          cd log-output          
          kustomize edit set image log-getter-image=eplol/log-getter:$GITHUB_SHA
          kustomize edit set image log-writer-image=eplol/log-writer:$GITHUB_SHA
          
      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'log-output/kustomization.yaml'
          message: New version released ${{ github.sha }}

  