name: Build and publish application

on:
  push:
    branches:
        - "main"
    tags:
        - "*"

permissions:
  contents: write
  
jobs:
  build-publish-getter:
    name: Build, Push, Release
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: eplol
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish backend
        run: |-
          cd project
          cd todo-backend
          docker build --tag "eplol/todo-backend:$GITHUB_SHA" .
          docker push "eplol/todo-backend:$GITHUB_SHA"
          cd ../todo-app
          docker build --tag "eplol/todo-app:$GITHUB_SHA" .
          docker push "eplol/todo-app:$GITHUB_SHA"
          cd ../broadcaster
          docker build --tag "eplol/broadcaster:$GITHUB_SHA" .
          docker push "eplol/broadcaster:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update image tags
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "TARGET_ENV=production" >> $GITHUB_ENV
          else
            echo "TARGET_ENV=staging" >> $GITHUB_ENV
          fi
      

      - name: Checkout Config Repo
        uses: actions/checkout@v4
        with:
          repository: eerojantunen/Kubernetescourse-config
          token: ${{ secrets.CONFIG_TOKEN }}
          path: config-temp

      - name: Update image tags
        run: |
          cd config-temp/project/overlays/${{ env.TARGET_ENV }}
          kustomize edit set image todo-app-image=eplol/todo-app:$GITHUB_SHA
          kustomize edit set image todo-backend-image=eplol/todo-backend:$GITHUB_SHA
          kustomize edit set image broadcaster-image=eplol/broadcaster:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          cwd: './config-temp'
          add: 'project/overlays'
          message: New version released ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.CONFIG_TOKEN }}